# Look in the tasks/setup.rb file for the various options that can be
# configured in this Rakefile. The .rake files in the tasks directory
# are where the options are used.

load 'tasks/setup.rb'

ensure_in_path 'lib'
require 'm80'

task :default => 'spec:run'

PROJ.name = 'm80'
PROJ.authors = 'bret@ckuru.com (who is writing this software)'
PROJ.email = 'bret@ckuru.com (your e-mail)'
PROJ.url = 'http://www.ckuru.com (project homepage)'
PROJ.rubyforge.name = 'm80'

PROJ.spec.opts << '--color'

# EOF
