#! /bin/bash
#
# M80 ---- see the License file for restrictions
#



PROGNAME=${0##*/}
TMPFILE=/tmp/${PROGNAME}.$$

if [ -n "${DEBUG}" ]; then	
	set -x
fi

PSCMD="ps axc"  








#
# $Header: /cvsroot/m80/m80/lib/shell/printmsg.sh,v 1.1.1.1 2003/11/26 22:24:33 bretweinraub Exp $
#
# Function:	printmsg
#
# Description:	generic error reporting routine.
#               BEWARE, white space is stripped and replaced with single spaces
#
# Call Signature:
#
# Side Effects:
#
# Assumptions:
#

printmsg () {
    if [ -z "${QUIET}" ]; then 
	if [ $# -ge 1 ]; then
	    /bin/echo -n ${M80_OVERRIDE_DOLLAR0:-$PROGNAME}:\($$\) >&2
		while [ $# -gt 0 ]; do /bin/echo -n " "$1 >&2 ; shift ; done
		if [ -z "${M80_SUPRESS_PERIOD}" ]; then
		    echo . >&2
		else
		    echo >&2
		fi
	fi
    fi
}


#
# Function:	cleanup
#
# Description:	generic KSH funtion for the end of a script
#
# History:	02.22.2000	bdw	passed error code through to localclean
#
# $Id: cleanup.sh,v 1.2 2004/04/06 22:42:02 bretweinraub Exp $
#

cleanup () {
    export EXITCODE=$1
    shift
    if [ $# -gt 0 ]; then
	printmsg $*
    fi
    if [ -n "${DQITMPFILE}" ]; then
	rm -f ${DQITMPFILE}
    fi
    if [ -n "${LOCALCLEAN}" ]; then
	localclean ${EXITCODE} # this function must be set
    fi
    if [ ${EXITCODE} -ne 0 ]; then
	# this is an error condition
	printmsg exiting with error code ${EXITCODE}
    else
	printmsg done
    fi
    exit ${EXITCODE}
}

trap "cleanup 1 caught signal" INT QUIT TERM HUP 2>&1 > /dev/null


require () {
    while [ $# -gt 0 ]; do
	#printmsg validating \$${1}
	derived=$(eval "echo \$"$1)
	if [ -z "$derived" ];then
	    printmsg \$${1} not defined
	    usage
	fi
	shift
    done
}



#
# Function:	docmd
#
# Description:	a generic wrapper for ksh functions
#
# $Id: docmd.sh,v 1.1.1.1 2003/11/26 22:24:33 bretweinraub Exp $

docmd () {
    if [ $# -lt 1 ]; then
	return
    fi
    #print ; eval "echo \* $*" ; print
    eval "echo '$*'"
    eval $*
    RETURNCODE=$?
    if [ $RETURNCODE -ne 0 ]; then
	cleanup $RETURNCODE command \"$*\" returned with error code $RETURNCODE
    fi
    return 0
}


#
# Function:	docmdi
#
# Description:	execute a command, but ignore the error code
#
# $Id: docmdi.sh,v 1.1.1.1 2003/11/26 22:24:33 bretweinraub Exp $

docmdi () {
    if [ $# -lt 1 ]; then
	return
    fi
#    print ; eval "echo \* $*" ; print
    eval "echo '$*'"
    eval $*
    export RETURNCODE=$?
    if [ $RETURNCODE -ne 0 ]; then
	printmsg command \"$*\" returned with error code $RETURNCODE, ignored
    fi
    return $RETURNCODE
}


#
# Function:	docmdqi
#
# Description:	execute a command quietly, but ignore the error code
#
# $Id: docmdqi.sh,v 1.1.1.1 2003/11/26 22:24:33 bretweinraub Exp $
#

docmdqi () {
    if [ $# -lt 1 ]; then return; fi
    DQITMPFILE=/tmp/${PROGNAME}.$$.dcmdqi
    eval $* 2>&1 > ${DQITMPFILE}
    export RETURNCODE=$?
    if [ ${RETURNCODE} -ne 0 ]; then
	cat ${DQITMPFILE} >&2
    fi
    rm -f ${DQITMPFILE}
    return $RETURNCODE
}


#
# Function:	checkfile
#
# Description:	This function is used to check whether some file ($2) or
#               directory meets some condition ($1).  If not print out an error
#               message ($3+).
#
# $Id: checkfile.sh,v 1.1.1.1 2003/11/26 22:24:33 bretweinraub Exp $

checkfile () {
    if [ $# -lt 2 ]; then
	cleanup 1 illegal arguments to the checkfile \(\) function
    fi
    FILE=$2
    if [ ! $1 $FILE ]; then
	shift; shift
	cleanup 1 file $FILE $*
    fi
}

checkNotFile () {
    if [ $# -lt 2 ]; then
	cleanup 1 illegal arguments to the checkNotfile \(\) function
    fi
    FILE=$2
    if [ $1 $FILE ]; then
	shift; shift
	cleanup 1 file $FILE $*
    fi
}




LOCALCLEAN=true
localclean () {
    rm -f /tmp/${PROGNAME}.$$*
    
}



usage () {
  printmsg  I am unhappy ...... a usage message follows for your benefit
  printmsg  Usage is -m {runMake=TRUE} 

printmsg command can be run with no arguments if one choses


  cleanup 1
} 

OPTIND=0
while getopts :m c 
    do case $c in        
	m) export runMake=TRUE;;
	:) printmsg $OPTARG requires a value
	   usage;;
	\?) printmsg unknown option $OPTARG
	   usage;;
    esac
done










localclean () {
    if [ -z "${NOCLEAN}" ]; then
	rm -rf $TMPFILE
    fi
}

testNum=0

dirs=$(find . -type d -name t)

unset M80_REPOSITORY
unset M80_BDF
unset M80_DIRECTORY
unset M80LOAD
unset M80PATH

pwd=$(pwd)

if [ -n "$runMake" ] ; then
    docmd make
fi

for dir in $dirs ; do
    for file in $dir/*.t; do
	tmpdir=$TMPFILE"/"$testNum
	mkdir -p $tmpdir
	cp -r $file* $tmpdir
        export additional_files_dir=`basename $file .t`
	unset STUPID_EXTRAS_DIR
        if test -d $dir/$additional_files_dir; then
            cp -R $dir/$additional_files_dir $tmpdir
	    export STUPID_EXTRAS_DIR=$additional_files_dir
        fi

	/bin/echo -n $PROGNAME: checking $file ....." "
# 	echo "(cd $tmpdir && env STUPID_SRC_DIR=$pwd/$dir bash $(basename $file))"
# 	(cd $tmpdir && env STUPID_SRC_DIR=$pwd/$dir bash $(basename $file))
# 	echo "(cd $tmpdir && env STUPID_SRC_DIR=$pwd/$dir $(basename $file))"
 	docmdqi "(cd $tmpdir && env STUPID_SRC_DIR=$pwd/$dir ./$(basename $file))"
	if [ $? -ne 0 ]; then
	    echo failed
	    printmsg test $file failed ... so sorry\; test directory was $tmpdir" "
	    exit 1
	fi
	echo success
	((testNum=$testNum+1))
    done
done


printmsg $testNum tests passed .... have fun

cleanup 0

# 
# =pod
# 
# =head1 NAME
# 
# stupidTestChassis - run tests
# 
# =head1 DESCRIPTION
# 
# Find all directories named 't' in directories below the current dir. For each file
# in that directory that has a '.t' extension, copy it into a temp directory and 
# execute that file. If there is a directory in the 't' directory with the same name
# as the test script minus the '.t' extension, then recursively copy that directory
# into the temp directory before test execution.
# If it exits with an error code, the test failed, and this script will exit with 1.
# 
# =head1 EXAMPLE
# 
# in ./t:
# 
#  sillytest.t
#  lotsoffilesintthistest.t
#  lotsoffilesintthistest/
#  smartertest.t
# 
# Then running stupidTestChassis at this node will create a temp directory for each
# test, copy it there and run it.
#
# =head1 ENVIRONMENT VARIABLES.
#
# NOCLEAN - if set the tmp directory is not deleted.
#
# STUPID_SRC_DIR - this is set to the directory the .t was found in
#
# STUPID_EXTRAS_DIR - this is set to the directory of the "extra" test files inside
# the "temp" dir inside of /tmp.
# 
# =cut
# 
