(defun pod-simple-template () 
  ""
  (interactive)
  ( insert "#\n")
  ( insert "# =pod\n")
  ( insert "#\n")
  ( insert "# =head1 NAME\n")
  ( insert "#\n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "# =head1 SYNOPSIS\n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "# =head1 OPTIONS AND ARGUMENTS\n")
  ( insert "# \n")
  ( insert "# =over 4\n")
  ( insert "# \n")
  ( insert "# =item \n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "# =item \n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "# =back\n")
  ( insert "# \n")
  ( insert "# =head1 DESCRIPTION\n")
  ( insert "# \n")
  ( insert "# \n")
  ( insert "#\n")
  ( insert "# =head1 EXAMPLES\n")
  ( insert "#\n")
  ( insert "# \n")
  ( insert "#\n")
  ( insert "# =head1 PREREQUISITES\n")
  ( insert "#\n")
  ( insert "# \n")
  ( insert "#\n")
  ( insert "# =cut \n")
  ( insert "# \n")
  ( previous-line 34)
  ( end-of-line)
  ( insert (buffer-name))
  ( next-line 4)
  ( end-of-line)
)
