# -*-makefile-*- #############################################################
#
# File:		Makefile (for Oracle Objects).
#
##############################################################################

include		depth.mk
include		$(SYSDEPTH)/system.mk
include		$(SUBSYSDEPTH)/subsys.mk
include		$(SUBSYSDEPTH)/oracle.mk
include 	$(MODDEPTH)/module.mk
include		$(SUBSYSDEPTH)/patch.mk

#uncomment this line if you know the CONNECTSTRING unequivocably from the environment
#CONNECTSTRING	= $(ORACLE_USER)/$(PASSWORD)@$(DSS_TNS)

include		$(MAKESNIPPETSDIR)/m4rules.mk
include		$(MAKESNIPPETSDIR)/codePatch.mk

