# -*-makefile-*- #############################################################
#
# File:		Makefile (for Oracle Objects).
#
##############################################################################

include		depth.mk
include		$(SYSDEPTH)/system.mk
include		$(SUBSYSDEPTH)/subsys.mk
include		$(SUBSYSDEPTH)/oracle.mk
include		$(MODDEPTH)/module.mk
include		$(SUBSYSDEPTH)/m4_to_sh.mk
include		$(SYSDEPTH)/leaf.mk

