
#
# Rules that pertain to Makefile.am (automake) files in the lib
# source tree.  
#


#
# The following derive a directories relative path relative to the 
# automake variable $(top_srcdir).
#
# This is appended to the $(pkgdatadir) variable to create the 
# installation path of the files in the directory of the makefile
# that includes them.  
#
# The net effect is that the directory structure in /usr/local/share/m80/lib
# will exactly mirror however the files in the distribution are organized.
#

relativePath = $(shell xx=$$(echo `cd $(top_srcdir) && pwd` | sed -e 's/\//\\\//g') ; pwd | sed -e 's/'$${xx}'//g')

localpkgdatadir = $(pkgdatadir)$(relativePath)

pkgdataDATA_INSTALL = $(INSTALL_DATA)


installpathtest :; echo $(localpkgdatadir)

#
# XXX

# PLEASE NOTE: We are overriding this rule that is generated by automake.
# This can be expected NOT to receive code updates from automake upgrades.
# 

install-pkgdataDATA: $(pkgdata_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(localpkgdatadir)
	@list='$(pkgdata_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(pkgdataDATA_INSTALL) $$d$$p $(DESTDIR)$(localpkgdatadir)/$$f"; \
	  $(pkgdataDATA_INSTALL) $$d$$p $(DESTDIR)$(localpkgdatadir)/$$f; \
	done

install-dist_pkgdataDATA: $(dist_pkgdata_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(localpkgdatadir)
	@list='$(dist_pkgdata_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(dist_pkgdataDATA_INSTALL) $$d$$p $(DESTDIR)$(localpkgdatadir)/$$f"; \
	  $(dist_pkgdataDATA_INSTALL) $$d$$p $(DESTDIR)$(localpkgdatadir)/$$f; \
	done

